--- # Gather EC2 facts
  - hosts: ww-dev-aws
    remote_user: ec2-user
    become: yes
    connection: ssh
    gather_facts: yes
    tasks:
    - name: Gather Ec2 facts
      action: ec2_facts
    - name: Display Ec2 Instance type
    - debug: 
        msg: "{{ ansible_ec2_instance_id }}"
