--- # start Stop Terminate Ec2 Instances
- hosts : localhost
  connection: local
  remote_user: zraja
  gather_facts: no
  become: zraja
  vars_files:
  - /home/zraja/{{creds}}.yml
  tasks:
    - name: List Running Instances
      ec2_remote_facts:
        aws_access_key: "{{ aws_key }}"
        aws_secret_key: "{{ aws_id }}"
        region: us-east-1
        filters:
          #vpc-id: vpc-56dba433
          instance-type: t2.micro
          instance-state-name: running
          #"tag:Name": "{{ instance_name }}"
      register: remote_facts
# show all known facts for this host
    - debug: var=[remote_facts]
