--- # start Stop Terminate Ec2 Instances
- hosts : localhost
  connection: local
  remote_user: sshuser
  gather_facts: no
  become: yes
  vars_files:
  - /home/zraja/slalomcreds.yml
  tasks:
    - name: List Running Instances
      ec2_remote_facts:
        aws_access_key: "{{ aws_key }}"
        aws_secret_key: "{{ aws_id }}"
        region: us-east-1
      register: ec2_facts
    - debug: 
        msg: "{{ remote_facts }}"
