--- # AwS Ec2 Instance Communication Shell Command Example
- hosts: slalom
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Execute s Shell Command for listing the directory
    shell : ls -al ~
    register: result
  - name: Display the result in JSON format
    debug: var=result
   
