# Install 
---
- hosts: terraform
  user: zuhaibakhtar
  sudo: true
  #become_method: sudo
  tasks:
    - name: Installs http-Debian
      apt: pkg=httpd,nginx state=absent #state=installed 
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install working-CentOS
      yum: pkg=nginx,apache2,nginx state=absent #installed
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
