#---
#- hosts: localhost
#  tasks:
#	- name: Install bind
#		 apt: pkgn=bind9 state= installed update_cache=true



---
- hosts: terraform
  user: zuhaibakhtar
  #sudo: true
  become_method: sudo
  tasks:
    - name: Installs http-Debian
      apt: pkg=nginx state=installed 
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install working-CentOS
      yum: pkg=httpd state=installed
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
