--- # first file
- hosts: webservers:gcloudservers
  become: yes
  vars:
    doc_root: /var/www/html/ansible/
    author: Zuhaib Raja 
  tasks:
  - name: Install nginx server
    yum: name=nginx state=present
    when: ansible_os_family == "RedHat"

  - name: Install apache server
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: start nginx server
    service: name=nginx enabled=yes state=started
    when: ansible_os_family == "RedHat"
  
  - name: start nginx server
    service: name=apache2 enabled=yes state=started
    when: ansible_os_family == "Debian"

  - name: copy index file
    template: src=templates/index.j2 dest={{ doc_root }}/index.html
    when: ansible_os_family == "Debian"
    notify:
      -  Restart Apache  
  
  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
 
- hosts: dbservers
  become: yes
  gather_facts: no  

  tasks:
  - name: install MYsql
    yum: name=mysql-server state=present

  - name: start mysql server
    service: name=mysqld enabled=true state=started

#- hosts: gcloudservers
#  become: yes
#  gather_facts: no

#  tasks:
#  - name: Install nginx server
#    apt: name=apache2 state=present

#  - name: start nginx server
#    service: name=apache2 enabled=yes state=started

- hosts: webservers:dbservers
  become: yes
  gather_facts: no

  tasks:
  - name: disable firewall
    service: name=firewalld state=stopped
